- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: fb_temp_ip
      prompt: Provide FlashBlade Temporary DHCP Address
      private: false
  tasks:

  - name: Create admin account.
    ansible.builtin.include_tasks:
      file: tasks/fb_version.yaml
