- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: fb_temp_ip
      prompt: Provide FlashBlade Temporary DHCP Address
      private: false
  tasks:

  - name: Set FlashBlade name
    purestorage.flashblade.purefb_bladename:
      name: "{{ fb_hostname }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
    ignore_errors: true

  - name: Assign NTP Servers
    purestorage.flashblade.purefb_ntp:
      ntp_servers: "{{ fb_ntp }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"

  - name: Assign TimeZone
    purestorage.flashblade.purefb_tz:
      timezone: "{{ fb_tz }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"

  - name: Configure Data Uplinks
    loop: "{{ fb_lag[0].ports }}"
    purefb_hardware:
      speed: "{{ fb_lag_lane_speed }}"
      ports: "{{ fb_lag_port_count }}"
      name: "{{ item }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"

  - name: Link Aggregation Group 
    ansible.builtin.include_tasks:
      file: tasks/fb_lag.yaml

  - name: Assign DNS Servers
    purestorage.flashblade.purefb_dns:
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
      domain: "{{ fb_dns.domain }}"
      nameservers: "{{ fb_dns.nameservers }}"

  - name: Create Subnets
    loop: "{{ fb_subnets }}"
    ansible.builtin.include_tasks:
      file: tasks/fb_subnet.yaml

  - name: Configure Admin Interfaces
    loop: "{{ fb_admin_network }}"
    ansible.builtin.include_tasks:
      file: tasks/fb_network.yaml

  - name: Configure SMTP 
    purestorage.flashblade.purefb_smtp:
      host: "{{ fb_smtp.relay_host }}"
      domain: "{{ fb_smtp.sender_domain }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"     

  - name: Configure Phonehome
    when: fb_support.phonehome_enabled == true
    purestorage.flashblade.purefb_phonehome:
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
      state: present

  - name: Configure Phonehome Proxy
    when: fb_support.phonehome_enabled == true and fb_support.proxy != ""
    purestorage.flashblade.purefb_proxy:
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
      host: "{{ fb_support.proxy }}"
      port: "{{ fb_support.proxy_port }}"
      secure: "{{ fb_support.proxy_secure }}"

  - name: Add email recipients on the alert list.
    loop: "{{ fb_alert_watchers }}"
    purestorage.flashblade.purefb_alert:
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
      address: "{{ item.address }}"
      severity: "{{ item.severity }}"
      enabled: true

  - name: Generate Admin account API token 
    when: fb_pureuser_api_token == true
    ansible.builtin.include_tasks:
      file: tasks/fb_pureuser.yaml

#  - name: Finalise the install and reboot.
#    ansible.builtin.include_tasks:
#      file: tasks/fb_finalize.yaml
