- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: fb_temp_ip
      prompt: Provide FlashBlade Temporary DHCP Address
      private: false
  tasks:

  - name: Set FlashBlade name
    purestorage.flashblade.purefb_bladename:
      name: "{{ fb_hostname }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"

  - name: Assign NTP Servers
    purestorage.flashblade.purefb_ntp:
      ntp_servers: "{{ fb_ntp }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"

  - name: Assign TimeZone
    purestorage.flashblade.purefb_tz:
      timezone: "{{ fb_tz }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"

  - name: Configure Data Uplinks
    loop: "{{ fb_lag[0].ports }}"
    purefb_hardware:
      speed: "{{ fb_lag_lane_speed }}"
      ports: "{{ fb_lag_port_count }}"
      name: "{{ item }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"

  - name: Link Aggregation Groups
    purestorage.flashblade.purefb_lag:
      ports: "{{ fb_lag[0].ports | regex_replace('.FM*.','') }}"
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"

  - name: Admin Network Subnets
    loop: "{{ fb_subnets }}"
    when: item.out_of_band == true
    purestorage.flashblade.purefb_subnet:
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
      name: "{{ item.name }}"
      prefix: "{{ item.prefix }}"
      gateway: "{{ item.gateway }}"
      vlan: "{{ item.vlan }}"

  - name: Remove LAG from Admin Subnet
    loop: "{{ fb_subnets }}"
    when: item.out_of_band == true
    ansible.builtin.include_tasks:
      file: tasks/fb_subnet.yaml

  - name: Data Network Subnets
    loop: "{{ fb_subnets }}"
    when: item.out_of_band == false
    purestorage.flashblade.purefb_subnet:
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
      name: "{{ item.name }}"
#      lag: "{{ item.lag }}"
#      mtu: "{{ item.mtu }}"
      prefix: "{{ item.prefix }}"
      gateway: "{{ item.gateway }}"
      vlan: "{{ item.vlan }}"

  - name: Configure Admin Interfaces
    loop: "{{ fb_admin_network }}"
    purefb_network:
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
      name: "{{ item.name }}"
      address: "{{ item.address }}"

  - name: Configure Data Interfaces
    loop: "{{ fb_data_network }}"
    purestorage.flashblade.purefb_network:
      fb_url: "{{ fb_temp_ip }}"
      api_token: "{{ ztp_token }}"
      name: "{{ item.name }}"
      address: "{{ item.address }}"
      
