        - name: Obtain API x-auth-token from FlashBlade
          uri:
            url: "https://{{ fb_temp_ip }}/api/login"
            method: POST
            body_format: json
            headers: 
              api-token: "{{ ztp_token }}"
            validate_certs: no
            return_content: yes
          register: login_response

        - name: Set API token as fact
          set_fact:
            session_token: "{{ login_response['x_auth_token'] }}"

        - name: Set Port Payload
          set_fact:
             payload1: "{{ payload1|default([]) + ['name: ' ~ item|string] }}"
          loop: "{{ fb_lag[0].ports }}"

        - name: Format Payload
          set_fact:
            payload: "{{ payload1|join(',') }}"

        - name: Create LAG. 
          uri:
            url: "https://{{ fb_temp_ip }}/api/{{ api_version }}/link-aggregation-groups?names={{ fb_lag[0].name }}"
            method: PATCH
            headers:
              Content-Type: application/json
              x-auth-token: "{{ session_token }}"
            validate_certs: no
            return_content: yes
            body_format: json
            body: 
              ports: 
                "{{ payload|split(',')|map('from_yaml')|list }}"

        #  ignore_errors: true
