        - name: Obtain API x-auth-token from FlashBlade
          uri:
            url: "https://{{ fb_temp_ip }}/api/login"
            method: POST
            body_format: json
            headers: 
              api-token: "{{ ztp_token }}"
            validate_certs: no
            return_content: yes
          register: login_response

        - name: Set API token as fact
          set_fact:
            session_token: "{{ login_response['x_auth_token'] }}"

        - name: Update Admin Interface. 
          uri:
            url: "https://{{ fb_temp_ip }}/api/{{ api_version }}/network-interfaces?names={{ item.name }}"
            method: PATCH
            headers:
              Content-Type: application/json
              x-auth-token: "{{ session_token }}"
            validate_certs: no
            return_content: yes
            body_format: json
            body: 
              address: "{{ item.address }}"
          ignore_errors: true

        - name: Get Interface 
          uri:
            url: "https://{{ fb_temp_ip }}/api/{{ api_version }}/network-interfaces?names={{ item.name }}"
            method: GET
            headers:
              Content-Type: application/json
              x-auth-token: "{{ session_token }}"
            validate_certs: no
            return_content: yes
            body_format: json
          ignore_errors: true
