        - name: Obtain API x-auth-token from FlashBlade
          uri:
            url: "https://{{ fb_temp_ip }}/api/login"
            method: POST
            body_format: json
            headers: 
              api-token: "{{ ztp_token }}"
            validate_certs: no
            return_content: yes
          register: login_response

        - name: Set API token as fact
          set_fact:
            session_token: "{{ login_response['x_auth_token'] }}"


       # - name: Create API Token for Pureuser v1. 
       #   uri:
       #     url: "https://{{ fb_temp_ip }}/api/1.12/admins?names=pureuser"
       #     method: PATCH
       #     headers:
       #       Content-Type: application/json
       #       x-auth-token: "{{ session_token }}"
       #     validate_certs: no
       #     return_content: yes
       #     body_format: json
       #     body:
       #       create_api_token: true

        - name: Create API Token for Admin User 
          uri:
            url: "https://{{ fb_temp_ip }}/api/{{ api_version }}/admins/api-tokens?admin_names=pureuser"
            method: POST
            headers:
              Content-Type: application/json
              x-auth-token: "{{ session_token }}"
            validate_certs: no
            return_content: yes
            body_format: json
           
          ignore_errors: true
