        - name: Obtain API x-auth-token from FlashBlade
          uri:
            url: "https://{{ fb_temp_ip }}/api/login"
            method: POST
            body_format: json
            headers: 
              api-token: "{{ ztp_token }}"
            validate_certs: no
            return_content: yes
          register: login_response

        - name: Set API token as fact
          set_fact:
            session_token: "{{ login_response['x_auth_token'] }}"


        - name: Validate Setup 
          uri:
            #url: "https://{{ fb_temp_ip }}/api/{{ api_version }}/setup/validation"
            url: "https://{{ fb_temp_ip }}/api/1.8.1/setup/validation"
            method: GET
            headers:
              Content-Type: application/json
              x-auth-token: "{{ session_token }}"
            validate_certs: no
            return_content: yes
            body_format: json
            body:
              setup_completed: true
              
